// <auto-generated />
using System;
using DecisionHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DecisionHelper.Migrations
{
    [DbContext(typeof(DecisionHelperDbContext))]
    [Migration("20260809005254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DecisionHelper.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AddedByPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedByPersonId");

                    b.HasIndex("NormalizedTitle", "ReleaseYear")
                        .IsUnique();

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("DecisionHelper.Models.MovieTag", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MovieTags");
                });

            modelBuilder.Entity("DecisionHelper.Models.MovieWatchStatus", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSeen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("MovieWatchStatuses");
                });

            modelBuilder.Entity("DecisionHelper.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("DecisionHelper.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName", "Kind")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DecisionHelper.Models.Movie", b =>
                {
                    b.HasOne("DecisionHelper.Models.Person", "AddedBy")
                        .WithMany("MoviesAdded")
                        .HasForeignKey("AddedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedBy");
                });

            modelBuilder.Entity("DecisionHelper.Models.MovieTag", b =>
                {
                    b.HasOne("DecisionHelper.Models.Movie", "Movie")
                        .WithMany("MovieTags")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionHelper.Models.Tag", "Tag")
                        .WithMany("MovieTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DecisionHelper.Models.MovieWatchStatus", b =>
                {
                    b.HasOne("DecisionHelper.Models.Movie", "Movie")
                        .WithMany("WatchStatuses")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DecisionHelper.Models.Person", "Person")
                        .WithMany("MovieWatchStatuses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DecisionHelper.Models.Movie", b =>
                {
                    b.Navigation("MovieTags");

                    b.Navigation("WatchStatuses");
                });

            modelBuilder.Entity("DecisionHelper.Models.Person", b =>
                {
                    b.Navigation("MovieWatchStatuses");

                    b.Navigation("MoviesAdded");
                });

            modelBuilder.Entity("DecisionHelper.Models.Tag", b =>
                {
                    b.Navigation("MovieTags");
                });
#pragma warning restore 612, 618
        }
    }
}
